Remember that you can report errors and get help in https://github.com/NicoSantangelo/sublime-gulp

08-31-2020 14:37:
fs.js:141
    throw new ERR_INVALID_CALLBACK();
    ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeCallback (fs.js:141:11)
    at Object.unlink (fs.js:959:14)
    at requireGulp (/Users/dengzhenhua/Library/Application Support/Sublime Text 3/Packages/Gulp/write_tasks_to_cache.js:30:12)
    at Object.<anonymous> (/Users/dengzhenhua/Library/Application Support/Sublime Text 3/Packages/Gulp/write_tasks_to_cache.js:83:12)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11
